version: 0.0
os: linux

files:
   - source: /
     destination: /home/ec2-user/api

hooks:
  AfterInstall:
    - location: migrate.sh
      runas: root
      timeline: 300
  ApplicationStart:
    - location: npm-start.sh
      runas: root
      timeout: 60