version: 0.0
os: linux

files:
   - source: /
     destination: /home/ec2-user/api

hooks:
  AfterInstall:
    - location: migrate.sh
      timeline: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: stop.sh
      timeout: 60
      runas: root